export const CONTEST_EXISTING = "Cuộc thi đã tồn tại trên hệ thống !"
export const COMPANY_ERROR = "Công ty tổ chức không tồn tại trên hệ thống hoặc không còn hoạt động !"
export  const ADD_CONTEST_SUCCES = "Thêm mới cuộc thi thành công !"
export const ADM_MESSAGE = "Vui lòng thông báo quản trị viên !"
export const GET_LIST_CONTEST_SUCCESS = "Lấy danh sách thành công !"