export const CONFLIT_COMPANY : string = "Công ty đã tồn tại trên hệ thống !"
export const ADD_COMPANY_SUCCESS : string = "Thêm mới công ty thành công !"
export const COMPANY_REM_EXIST : string = "Giới thiệu công ty tồn tại!"
export const GET_LIST_COMPANY_SUCCESS : string = "Láy danh sách tổ chức thành công !"
export const GET_DETAILS_COMPANY_SUCCESS : string = "Lấy thông tin tổ chức thành công !"
export const UPDATE_COMPANY_SUCCESS:  string = "Cập nhật thông tin thành công !"